### ISSUE TITLE
sense-images-links-extension need to increase the columns to 50 (currently it works only 10)

### ISSUE THREAD

**Issue by devarasu07** [danielpilla/sense-images-links-extension#4]
Hi,

i've similar kind of requirment, using below attached extension is working fine but no.of columns are limited to 10 column only. if i add more than 10 fields then simple table extension script not working (refer screen image). do you have any other extension or enhanced script. thanks in advance 
https://github.com/danielpilla/sense-images-links-extension

raised forum thread about the issue
https://community.qlik.com/thread/244558

**Comment by danielpilla** [comment]
You can adjust how many columns in the JS file by changing the "qWidth" setting. It is currently set to 10, with a "qHeight" of 500. Note that the initial data fetch caps at 10k cells in the cube, so 1 column at 500 cells is 500, 10 columns at 500 rows is 5k, etc. Once you modify "qWidth" you will need to close Qlik Sense, reopen it, and convert the old rendering of the table into the new rendering by dragging and dropping and selecting convert (if you are planning on altering an existing table with the updated extension code).

Screenshot: http://imgur.com/CdxHA99
